### ISSUE TITLE
текст в колонках

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/acme-css#2]
https://github.com/DenisPitsul/acme-css/blob/45bcfa68b11901e05ce716d5985d8d3e77b10584/index.html#L26-L35
- за текстом видно, що тут один абзац, а не два (нема поділу на речення). Тут краще підійде [поділ на колонки](https://developer.mozilla.org/en-US/docs/Web/CSS/columns) - дуже гнучка штука, яку навіть можна налаштувати так, щоб текст сам перебудовувався в таку кількість стовпців, скільки влізе при поточній ширині в'юпорта.

**Comment by DenisPitsul** [comment]
Finxed in commit:
https://github.com/DenisPitsul/acme-css/commit/23babc9c7cd7c943efe92290b10b3bd2dbfd0be4

**Comment by pecourses** [comment]
Якщо у нас не жорсткі брекпойнти, то часто буває зручно обходитись без медіазапитів, де це можливо:
![image](https://github.com/DenisPitsul/acme-css/assets/67504221/d72c75df-b359-4c68-9ad8-c62fa58c2c92)
Тобто вказати мінімальну допустиму ширину колонки, і з кількістю `auto` буде стільки колонок, скільки поміститься 🙂.

Доречі, коли не жорсткі брекпойнти, дуже зручно і флексами в двох нижніх секціях без медіазапитів:
![image](https://github.com/DenisPitsul/acme-css/assets/67504221/90bd9b1f-f501-4986-abf4-338f8e070487)
Тоді код виходе лаконічнішим)

**Comment by DenisPitsul** [comment]
Added changes according to recomendations:
https://github.com/DenisPitsul/acme-css/commit/65e6704889f7d9c87da75f13351173d1a05a3f63
